jobs:
  include:
  - stage: "Deploy"
    script: skip
    language: generic
    if: branch = master
    env: ELASTIC_STACK_VERSION=7.5.1
    deploy:
      provider: script
      script: .ci/docker-publish.sh
      skip_cleanup: true
